name: Auto Create Pull Request

on:
  push:
    branches:
      - 'feature/*'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Auto PR - Mise à jour depuis feature"
          body: |
            Pull Request générée automatiquement via CI  
            Cible : dev
          head: ${{ github.ref }}
          base: dev
          draft: false
